require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SessionsController, type: :controller do

  before do
    @user = create(:user)
  end

  # This should return the minimal set of attributes required to create a valid
  # Session. As you add validations to Session, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { email: @user.email, password: @user.password }
  end

  let(:invalid_attributes) do
    { email: 'test-email@email.com', password: 'wrong-password' }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SessionsController. Be sure to keep this updated too.
  let(:valid_session) { }

  describe "GET #index" do
    it "assigns all sessions as @sessions" do
      session = Session.create! valid_attributes
      get :index, {}, { id: session.id } 
      expect(assigns(:sessions)).to eq([session])
    end
  end

  describe "GET #show" do
    it "assigns the requested session as @session" do
      session = Session.create! valid_attributes
      get :show, {:id => session.to_param}, { id: session.id }
      expect(assigns(:session)).to eq(session)
    end
  end

  describe "GET #new" do
    it "assigns a new session as @session" do
      get :new, {}, valid_session
      expect(assigns(:session)).to be_a_new(Session)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Session" do
        expect {
          post :create, {:session => valid_attributes}, valid_session
        }.to change(Session, :count).by(1)
      end

      it "assigns a newly created session as @session" do
        post :create, {:session => valid_attributes}, valid_session
        expect(assigns(:session)).to be_a(Session)
        expect(assigns(:session)).to be_persisted
      end

      it "redirects to the created session" do
        post :create, {:session => valid_attributes}, valid_session
        expect(response).to redirect_to(Session.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved session as @session" do
        post :create, {:session => invalid_attributes}, valid_session
        expect(assigns(:session)).to be_a_new(Session)
      end

      it "re-renders the 'new' template" do
        post :create, {:session => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

end
